import { MigrationInterface, QueryRunner } from "typeorm";

export class AddEntities1705619510391 implements MigrationInterface {
    name = 'AddEntities1705619510391'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Activity" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3603ebbaf4b4db169e33bc148a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Service" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "avatar" character varying, "duration" integer NOT NULL, "break" integer, "price" numeric(10,2) NOT NULL, "desc" character varying, "images" jsonb DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, "categoryId" integer, CONSTRAINT "PK_c77cf540affcc8a04962fc6e9f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78214d6bf79e4a09b5901ab270" ON "Service" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_67f107076d6bd8d3925d4c1106" ON "Service" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "Resource" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "avatar" character varying, "desc" character varying, "images" jsonb DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, CONSTRAINT "PK_c029bb9649165945fc2fa675de0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98011dab4791d2a82ffe5141ee" ON "Resource" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "Schedule" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "year" integer NOT NULL, "month" integer NOT NULL, "dates" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, "employeesId" integer, "resourceId" integer, CONSTRAINT "PK_1e0db675cb5a22276ffd69b1a5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93bdbe30fd79d0b4b128f9fa4f" ON "Schedule" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "Employee" ("id" SERIAL NOT NULL, "jobTitle" character varying NOT NULL, "info" character varying, "provider" boolean NOT NULL DEFAULT false, "status" character varying NOT NULL DEFAULT 'working', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, "categoryId" integer, "companyId" integer, CONSTRAINT "PK_9a993c20751b9867abc60108433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1ec0cb63387d4c8bb2892bc00" ON "Employee" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe6037e394d7ffa899f02fb699" ON "Employee" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0183e9f89fdcfc0bbb1851c23" ON "Employee" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "Product" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "avatar" character varying, "desc" character varying, "images" jsonb DEFAULT '[]', "price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL, "article" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, "categoryId" integer, CONSTRAINT "PK_9fc040db7872192bbc26c515710" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1dff7dcde01403b365c4e2706d" ON "Product" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_896e2e0f6dfa6f80117a79e1d7" ON "Product" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_baf18ec56c390f50ce1f94c687" ON "Product" ("article") `);
        await queryRunner.query(`CREATE TABLE "Category" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c2727780c5b9b0c564c29a4977c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Action" ("id" SERIAL NOT NULL, "desc" character varying, "type" character varying NOT NULL, "date" character varying NOT NULL, "price" character varying NOT NULL, "discount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, "employeeId" integer, CONSTRAINT "PK_af6e2515edb74ee3377aa7c60bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c24d99248e6fe2cd9f87b98cbe" ON "Action" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "resources_services_service" ("resourceId" integer NOT NULL, "serviceId" integer NOT NULL, CONSTRAINT "PK_d61bcdddf8b15ab52d1f749d950" PRIMARY KEY ("resourceId", "serviceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_058117041c37eee012cf95445c" ON "resources_services_service" ("resourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdd218bd99409767870e6794d9" ON "resources_services_service" ("serviceId") `);
        await queryRunner.query(`CREATE TABLE "employee_services_service" ("employeeId" integer NOT NULL, "serviceId" integer NOT NULL, CONSTRAINT "PK_cb7e177fdc44118e14d7ab14f33" PRIMARY KEY ("employeeId", "serviceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d1677a62a4da3198008c773d07" ON "employee_services_service" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a037140d8c4cfe519b515db0c5" ON "employee_services_service" ("serviceId") `);
        await queryRunner.query(`CREATE TABLE "company_activity_service" ("companyId" integer NOT NULL, "activityId" integer NOT NULL, CONSTRAINT "PK_7c1a9c9a16b484e60a8a7fe1f9a" PRIMARY KEY ("companyId", "activityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40a203cb51810e98d9c1796148" ON "company_activity_service" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d14b5d07b407bcfabbb180b7d2" ON "company_activity_service" ("activityId") `);
        await queryRunner.query(`CREATE TABLE "company_category_service" ("companyId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_3b81dfd154858c279e07661b0cd" PRIMARY KEY ("companyId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_731503b7cc73318060ac42ccda" ON "company_category_service" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f65ae9232cbeace61ce9c6ea84" ON "company_category_service" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "action_resource_service" ("actionId" integer NOT NULL, "resourceId" integer NOT NULL, CONSTRAINT "PK_1b26ea2472ae06abfd2d3d898f0" PRIMARY KEY ("actionId", "resourceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c2dab72c7f20390fb2b2c8ecd8" ON "action_resource_service" ("actionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5181ba3a9bf25fd840b240895" ON "action_resource_service" ("resourceId") `);
        await queryRunner.query(`ALTER TABLE "Company" ADD "phone" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Company" ADD "address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Company" ADD "workingHours" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Company" ADD "desc" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Company" ADD "avatar" character varying`);
        await queryRunner.query(`ALTER TABLE "Company" ADD "images" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "Client" ADD "avatar" character varying DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "Client" ADD "birthday" character varying DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "Client" ADD "gender" character varying DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "Client" ADD "discount" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "Client" ADD "comment" character varying DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "Service" ADD CONSTRAINT "FK_78214d6bf79e4a09b5901ab270a" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "Service" ADD CONSTRAINT "FK_67f107076d6bd8d3925d4c11064" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "Resource" ADD CONSTRAINT "FK_98011dab4791d2a82ffe5141ee2" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Schedule" ADD CONSTRAINT "FK_93bdbe30fd79d0b4b128f9fa4f0" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Schedule" ADD CONSTRAINT "FK_bd37610f04f78c77edf95077615" FOREIGN KEY ("employeesId") REFERENCES "Employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Schedule" ADD CONSTRAINT "FK_48683fa37f06b2c384fbeda53bf" FOREIGN KEY ("resourceId") REFERENCES "Resource"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Employee" ADD CONSTRAINT "FK_c1ec0cb63387d4c8bb2892bc002" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Employee" ADD CONSTRAINT "FK_fe6037e394d7ffa899f02fb6999" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Employee" ADD CONSTRAINT "FK_b0183e9f89fdcfc0bbb1851c23c" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "Product" ADD CONSTRAINT "FK_1dff7dcde01403b365c4e2706df" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Product" ADD CONSTRAINT "FK_896e2e0f6dfa6f80117a79e1d7e" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Action" ADD CONSTRAINT "FK_c24d99248e6fe2cd9f87b98cbe9" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Action" ADD CONSTRAINT "FK_a84cebf1fd79fa94e187eb23a56" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resources_services_service" ADD CONSTRAINT "FK_058117041c37eee012cf95445c3" FOREIGN KEY ("resourceId") REFERENCES "Resource"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "resources_services_service" ADD CONSTRAINT "FK_bdd218bd99409767870e6794d9e" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee_services_service" ADD CONSTRAINT "FK_d1677a62a4da3198008c773d07c" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee_services_service" ADD CONSTRAINT "FK_a037140d8c4cfe519b515db0c59" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_activity_service" ADD CONSTRAINT "FK_40a203cb51810e98d9c1796148b" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "company_activity_service" ADD CONSTRAINT "FK_d14b5d07b407bcfabbb180b7d25" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_category_service" ADD CONSTRAINT "FK_731503b7cc73318060ac42ccdae" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "company_category_service" ADD CONSTRAINT "FK_f65ae9232cbeace61ce9c6ea848" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action_resource_service" ADD CONSTRAINT "FK_c2dab72c7f20390fb2b2c8ecd82" FOREIGN KEY ("actionId") REFERENCES "Action"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "action_resource_service" ADD CONSTRAINT "FK_e5181ba3a9bf25fd840b2408954" FOREIGN KEY ("resourceId") REFERENCES "Resource"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "action_resource_service" DROP CONSTRAINT "FK_e5181ba3a9bf25fd840b2408954"`);
        await queryRunner.query(`ALTER TABLE "action_resource_service" DROP CONSTRAINT "FK_c2dab72c7f20390fb2b2c8ecd82"`);
        await queryRunner.query(`ALTER TABLE "company_category_service" DROP CONSTRAINT "FK_f65ae9232cbeace61ce9c6ea848"`);
        await queryRunner.query(`ALTER TABLE "company_category_service" DROP CONSTRAINT "FK_731503b7cc73318060ac42ccdae"`);
        await queryRunner.query(`ALTER TABLE "company_activity_service" DROP CONSTRAINT "FK_d14b5d07b407bcfabbb180b7d25"`);
        await queryRunner.query(`ALTER TABLE "company_activity_service" DROP CONSTRAINT "FK_40a203cb51810e98d9c1796148b"`);
        await queryRunner.query(`ALTER TABLE "employee_services_service" DROP CONSTRAINT "FK_a037140d8c4cfe519b515db0c59"`);
        await queryRunner.query(`ALTER TABLE "employee_services_service" DROP CONSTRAINT "FK_d1677a62a4da3198008c773d07c"`);
        await queryRunner.query(`ALTER TABLE "resources_services_service" DROP CONSTRAINT "FK_bdd218bd99409767870e6794d9e"`);
        await queryRunner.query(`ALTER TABLE "resources_services_service" DROP CONSTRAINT "FK_058117041c37eee012cf95445c3"`);
        await queryRunner.query(`ALTER TABLE "Action" DROP CONSTRAINT "FK_a84cebf1fd79fa94e187eb23a56"`);
        await queryRunner.query(`ALTER TABLE "Action" DROP CONSTRAINT "FK_c24d99248e6fe2cd9f87b98cbe9"`);
        await queryRunner.query(`ALTER TABLE "Product" DROP CONSTRAINT "FK_896e2e0f6dfa6f80117a79e1d7e"`);
        await queryRunner.query(`ALTER TABLE "Product" DROP CONSTRAINT "FK_1dff7dcde01403b365c4e2706df"`);
        await queryRunner.query(`ALTER TABLE "Employee" DROP CONSTRAINT "FK_b0183e9f89fdcfc0bbb1851c23c"`);
        await queryRunner.query(`ALTER TABLE "Employee" DROP CONSTRAINT "FK_fe6037e394d7ffa899f02fb6999"`);
        await queryRunner.query(`ALTER TABLE "Employee" DROP CONSTRAINT "FK_c1ec0cb63387d4c8bb2892bc002"`);
        await queryRunner.query(`ALTER TABLE "Schedule" DROP CONSTRAINT "FK_48683fa37f06b2c384fbeda53bf"`);
        await queryRunner.query(`ALTER TABLE "Schedule" DROP CONSTRAINT "FK_bd37610f04f78c77edf95077615"`);
        await queryRunner.query(`ALTER TABLE "Schedule" DROP CONSTRAINT "FK_93bdbe30fd79d0b4b128f9fa4f0"`);
        await queryRunner.query(`ALTER TABLE "Resource" DROP CONSTRAINT "FK_98011dab4791d2a82ffe5141ee2"`);
        await queryRunner.query(`ALTER TABLE "Service" DROP CONSTRAINT "FK_67f107076d6bd8d3925d4c11064"`);
        await queryRunner.query(`ALTER TABLE "Service" DROP CONSTRAINT "FK_78214d6bf79e4a09b5901ab270a"`);
        await queryRunner.query(`ALTER TABLE "Client" DROP COLUMN "comment"`);
        await queryRunner.query(`ALTER TABLE "Client" DROP COLUMN "discount"`);
        await queryRunner.query(`ALTER TABLE "Client" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "Client" DROP COLUMN "birthday"`);
        await queryRunner.query(`ALTER TABLE "Client" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "Company" DROP COLUMN "images"`);
        await queryRunner.query(`ALTER TABLE "Company" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "Company" DROP COLUMN "desc"`);
        await queryRunner.query(`ALTER TABLE "Company" DROP COLUMN "workingHours"`);
        await queryRunner.query(`ALTER TABLE "Company" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "Company" DROP COLUMN "phone"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5181ba3a9bf25fd840b240895"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2dab72c7f20390fb2b2c8ecd8"`);
        await queryRunner.query(`DROP TABLE "action_resource_service"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f65ae9232cbeace61ce9c6ea84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_731503b7cc73318060ac42ccda"`);
        await queryRunner.query(`DROP TABLE "company_category_service"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d14b5d07b407bcfabbb180b7d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40a203cb51810e98d9c1796148"`);
        await queryRunner.query(`DROP TABLE "company_activity_service"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a037140d8c4cfe519b515db0c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1677a62a4da3198008c773d07"`);
        await queryRunner.query(`DROP TABLE "employee_services_service"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdd218bd99409767870e6794d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_058117041c37eee012cf95445c"`);
        await queryRunner.query(`DROP TABLE "resources_services_service"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c24d99248e6fe2cd9f87b98cbe"`);
        await queryRunner.query(`DROP TABLE "Action"`);
        await queryRunner.query(`DROP TABLE "Category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_baf18ec56c390f50ce1f94c687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_896e2e0f6dfa6f80117a79e1d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1dff7dcde01403b365c4e2706d"`);
        await queryRunner.query(`DROP TABLE "Product"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0183e9f89fdcfc0bbb1851c23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe6037e394d7ffa899f02fb699"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1ec0cb63387d4c8bb2892bc00"`);
        await queryRunner.query(`DROP TABLE "Employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93bdbe30fd79d0b4b128f9fa4f"`);
        await queryRunner.query(`DROP TABLE "Schedule"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98011dab4791d2a82ffe5141ee"`);
        await queryRunner.query(`DROP TABLE "Resource"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67f107076d6bd8d3925d4c1106"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78214d6bf79e4a09b5901ab270"`);
        await queryRunner.query(`DROP TABLE "Service"`);
        await queryRunner.query(`DROP TABLE "Activity"`);
    }

}
